[book]
authors = ["Tom Kunc"]
language = "en"
src = "src"
title = "LifetimeKata"

[build]
extra-watch-dirs = ["../exercises"]

[preprocessor.footnote]

[output.html]
no-section-label = true
site-url = "/lifetimekata/"
git-repository-url = "https://github.com/thinkgos/lifetimekata"

[output.html.playground]
editable = true